#ifndef POLYGLOT_TURTLE_XIAO_PROJ_CONFIG_H
#define POLYGLOT_TURTLE_XIAO_PROJ_CONFIG_H

#define DMA_CHANNEL_USART       0
#define DMA_CHANNEL_SPI_WRITE   1
#define DMA_CHANNEL_SPI_READ    2



#endif //POLYGLOT_TURTLE_XIAO_PROJ_CONFIG_H
